Update hehe

diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -1,37 +1,48 @@
 #!/bin/bash
 clear
-[[ "$(whoami)" != "root" ]] && {
-echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33m◇ YOU NEED TO RUN AS ROOT!\033[0m"
-rm $HOME/hehe > /dev/null 2>&1; exit 0
+# Function to display a progress bar
+fun_bar() {
+    comando[0]="$1"
+    comando[1]="$2"
+    
+    (
+    [[ -e $HOME/fim ]] && rm $HOME/fim
+    ${comando[0]} -y > /dev/null 2>&1
+    ${comando[1]} -y > /dev/null 2>&1
+    touch $HOME/fim
+    ) > /dev/null 2>&1 &
+    
+    tput civis
+    echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
+    while true; do
+        for ((i=0; i<18; i++)); do
+            echo -ne "\033[1;31m#"
+            sleep 0.1s
+        done
+        [[ -e $HOME/fim ]] && rm $HOME/fim && break
+        echo -e "\033[1;33m]"
+        sleep 1s
+        tput cuu1
+        tput dl1
+        echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
+    done
+    echo -e "\033[1;33m]\033[1;37m -\033[1;32m◇ DONE!\033[1;37m"
+    tput cnorm
 }
-_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
-cd $HOME
-fun_bar () {
-comando[0]="$1"
-comando[1]="$2"
-(
-[[ -e $HOME/fim ]] && rm $HOME/fim
-${comando[0]} -y > /dev/null 2>&1
-${comando[1]} -y > /dev/null 2>&1
-touch $HOME/fim
-) > /dev/null 2>&1 &
-tput civis
-echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
-while true; do
-for((i=0; i<18; i++)); do
-echo -ne "\033[1;31m#"
-sleep 0.1s
-done
-[[ -e $HOME/fim ]] && rm $HOME/fim && break
-echo -e "\033[1;33m]"
-sleep 1s
-tput cuu1
-tput dl1
-echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
-done
-echo -e "\033[1;33m]\033[1;37m -\033[1;32m◇ DONE!\033[1;37m"
-tput cnorm
+
+# Function to verify key
+verif_key() {
+    krm=$(echo '5:q-3gs2.o7%8:1'|rev)
+    chmod +x $_Ink/list > /dev/null 2>&1
+    [[ ! -e "$_Ink/list" ]] && {
+        echo -e "\n\033[1;31m◇ KEY INVALID!\033[0m"
+        rm -rf $HOME/hehe > /dev/null 2>&1
+        sleep 2
+        clear
+        exit 1
+    }
 }
+
 send_code_telegram() {
     local telegram_handle=$1
     random_code=$(shuf -i 100000-999999 -n 1)  # Generate random 6-digit code
@@ -63,16 +74,13 @@ if [[ "$random_code" != "$random_code" ]]; then
     echo -e "\033[1;35mInvalid code. Installation aborted.\033[0m"
     exit 1
 fi
+clear
+# Variable Initialization
+_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev)
+_Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig')
+_1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
 
-function verif_key () {
-krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
-[[ ! -e "$_Ink/list" ]] && {
-echo -e "\n\033[1;31m◇ KEY INVALID!\033[0m"
-rm -rf $HOME/hehe > /dev/null 2>&1
-sleep 2
-clear; exit 1
-}
-}
+
 echo -e "\033[1;31m\033[0m"
 tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "◇─────────ㅤ🪐ㅤWelcome To GOD-TECH VPS MANAGERㅤ🪐ㅤ─────────◇" ; tput sgr0
 echo -e "\033[1;34m◇───────────────────────────────────────────────◇\033[0m"
