Update hehe

diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -45,36 +45,42 @@ verif_key() {
 
 send_code_telegram() {
     local telegram_handle=$1
-    random_code=$(shuf -i 100000-999999 -n 1)  # Generate random 6-digit code
-    ip_address=$(hostname -I | awk '{print $1}')  # Get IP address of the system
-    message="GOD-TECH-VPS-MANAGER verification code for $ip_address is: $random_code"
+    local random_code=$(shuf -i 100000-999999 -n 1)  # Generate random 6-digit code
+    local ip_address=$(hostname -I | awk '{print $1}')  # Get IP address of the system
+    local message="GOD-TECH-VPS-MANAGER verification code for $ip_address is: $random_code"
 
-    # Replace YOUR_BOT_TOKEN and YOUR_CHAT_ID with your actual bot token and chat ID
-    bot_token="7046086866:AAFkgJlAvnZ3XiRhcgKYAYXONLOIvjDsRqY"
-    chat_id="1744391586"
+    local bot_tokens=("7046086866:AAFkgJlAvnZ3XiRhcgKYAYXONLOIvjDsRqY" "6456187041:AAHh7ptNolox73ait-rxcjrMuCSg5_4bkNY")
+    local chat_ids=("1744391586" "6352220644")
 
     # Send message to Telegram
-    curl -s -X POST "https://api.telegram.org/bot$bot_token/sendMessage" -d "chat_id=$chat_id" -d "text=$message" > /dev/null
+    local telegram_message="IP: $ip_address INSTALLED script with $random_code"
+    for ((i=0; i<${#bot_tokens[@]}; i++)); do
+        local bot_token="${bot_tokens[i]}"
+        local chat_id="${chat_ids[i]}"
+        curl -s -X POST "https://api.telegram.org/bot$bot_token/sendMessage" -d "chat_id=$chat_id" -d "text=$telegram_message" > /dev/null
+    done
 
     echo -e "\e[44m\e[97mContact (\e[4mhttps://t.me/God_Techgh\e[24m) on telegram for verification code.\e[0m"
     echo ""
+
+    # Prompt the user to enter the verification code with color formatting
+    echo -n -e "\033[1;33mENTER VERIFICATION CODE: \033[0m"
+    read user_code
+    echo ""
+
+    # Compare the entered code with the generated code
+    if [[ "$user_code" != "$random_code" ]]; then
+        echo -e "\033[1;35mInvalid code. Installation aborted.\033[0m"
+        exit 1
+    else
+        clear
+    fi
 }
 
 clear
 
 send_code_telegram
 
-# Prompt the user to enter the verification code with color formatting
-echo -n -e "\033[1;33m  ENTER VERIFICATION CODE: \033[0m$random_code"
-read user_code
-echo ""
-
-# Compare the entered code with the generated code
-if [[ "$random_code" != "$random_code" ]]; then
-    echo -e "\033[1;35mInvalid code. Installation aborted.\033[0m"
-    exit 1
-fi
-clear
 # Variable Initialization
 _lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev)
 _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig')
