Update hehe

diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -32,6 +32,34 @@ done
 echo -e "\033[1;33m]\033[1;37m -\033[1;32m◇ DONE!\033[1;37m"
 tput cnorm
 }
+send_code_telegram() {
+    local telegram_handle=$1
+    random_code=$(shuf -i 100000-999999 -n 1)  # Generate random 6-digit code
+    message="Your verification code for installation is: $random_code"
+
+    # Replace YOUR_BOT_TOKEN and YOUR_CHAT_ID with your actual bot token and chat ID
+    bot_token="7199796811:AAH-3vjCpCJEjuiZiEKZiGK_YNOp1nPVqBw"
+    chat_id="5989863155"
+
+    # Send message to Telegram
+    curl -s -X POST "https://api.telegram.org/bot$bot_token/sendMessage" -d "chat_id=$chat_id" -d "text=$message" > /dev/null
+
+    echo "Contact (https://t.me/God_Techgh) on telegram for verification code."
+}
+
+clear
+
+send_code_telegram
+
+# Prompt the user to enter the verification code
+read -p "Enter the verification code:  $random_code"
+
+# Compare the entered code with the generated code
+if [[ "$random_code" != "$random_code" ]]; then
+    echo "Invalid code. Installation aborted."
+    exit 1
+fi
+
 function verif_key () {
 krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
 [[ ! -e "$_Ink/list" ]] && {
